OPCAO=-std=c++11
All:
	g++ parametrico.cpp $(OPCAO) -o parametrico
	g++ inclusao.cpp $(OPCAO) -o transformers
	g++ ad_hoc.cpp $(OPCAO) -o ad_hoc
	g++ coercao.cpp $(OPCAO) -o coercao
clean:
	rm -rf *~ parametrico coercao ad_hoc transformers
