All:
	g++ Atribuicao.cpp --std=c++11 -o Atribuicao
	g++ cadastro01.cpp --std=c++11 -o cadastro01
	g++ cadastro02.cpp --std=c++11 -o cadastro02
	g++ cadastro03.cpp --std=c++11 -o cadastro03
	g++ cadastro04.cpp --std=c++11 -o cadastro04
run:
	./cadastro01
run2:
	./cadastro02
run3:
	./cadastro03
run4:
	./cadastro04
clean:
	rm Atribuicao cadastro01  cadastro02  cadastro03 cadastro04 *~ 
