All:
	g++ -Wall cadastroOO.cpp --std=c++11 -o cadastroOO
	g++ -Wall -c cadastro.cpp --std=c++11
	g++ -Wall -c main.cpp --std=c++11
	g++ -Wall cadastro.o main.o --std=c++11 -o cadastro
run:
	./cadastro
clean:
	rm cadastroOO cadastro *~ *.o
