All:
	g++ -Wall -g -c carro.cpp --std=c++11 	# Gerar carro.o
	g++ -Wall -g -c main.cpp --std=c++11 	# Gerar main.o
	g++ -Wall -g carro.o main.o --std=c++11  -o carro
run:
	./carro
clean:
	rm carro *~ *.o
