All:
	g++ OiMundo.cpp -o oiMundo
	g++ OiMundo2.cpp -o oiMundo2
	g++ Soma.cpp -o soma
	g++ Vinculacao.cpp -o vinculacao
	g++ size.cpp -o size
	g++ Passagem.cpp -o passagem
clean:
	rm -rf oiMundo oiMundo2 size soma vinculacao passagem *~ 
